import type { CatalogItem, AreaCode } from './types';

export const OFFICIAL_AREAS: AreaCode[] = [
  'GAB',
  'UAUD',
  'URI',
  'UGE',
  'UMC',
  'AJUR',
  'UGP',
  'UAS',
  'UGOC',
  'UTIC',
  'URC',
  'UAC',
  'UNIDADES_REGIONAIS'
];

export const NINE_BOX_QUADRANTS = [
  { x: 'low', y: 'low', label: 'Baixa Aderência' },
  { x: 'mid', y: 'low', label: 'Especialista Técnico sem Perfil de Liderança' },
  { x: 'high', y: 'low', label: 'Risco de Liderança' },
  { x: 'low', y: 'mid', label: 'Desenvolvimento Direcionado' },
  { x: 'mid', y: 'mid', label: 'Potencial de Médio Prazo' },
  { x: 'high', y: 'mid', label: 'Destaque Técnico, lapidar liderança' },
  { x: 'low', y: 'high', label: 'Potencial de Curto Prazo (gap técnico)' },
  { x: 'mid', y: 'high', label: 'Pronto em Desenvolvimento' },
  { x: 'high', y: 'high', label: 'Alta Prontidão' }
];

export const CATALOG_ITEMS: CatalogItem[] = [
  { id: 'mba-strategic', label: 'MBA Estratégia Corporativa', group: 'postMBA', classification: 'transversal' },
  { id: 'mba-finance', label: 'MBA Finanças e Controladoria', group: 'postMBA', classification: 'area-specific', area: 'UGE' },
  { id: 'mba-auditoria', label: 'MBA Auditoria Interna', group: 'postMBA', classification: 'area-specific', area: 'UAUD' },
  { id: 'mba-governance', label: 'MBA Governança e Compliance', group: 'postMBA', classification: 'transversal' },
  { id: 'mba-gestao-publica', label: 'MBA Gestão Pública', group: 'postMBA', classification: 'transversal' },
  { id: 'mba-ti', label: 'MBA em Gestão de Tecnologia da Informação', group: 'postMBA', classification: 'area-specific', area: 'UTIC' },
  { id: 'curso-lideranca', label: 'Curso de Liderança Estratégica', group: 'course', classification: 'transversal' },
  { id: 'curso-gestao-projetos', label: 'Curso de Gestão de Projetos Estratégicos', group: 'course', classification: 'area-specific', area: 'UGP' },
  { id: 'curso-governanca', label: 'Curso de Governança Corporativa', group: 'course', classification: 'transversal' },
  { id: 'curso-comunicacao', label: 'Curso de Comunicação Executiva', group: 'course', classification: 'transversal' },
  { id: 'curso-negocios', label: 'Curso de Análise de Negócios', group: 'course', classification: 'area-specific', area: 'UGE' },
  { id: 'curso-risco', label: 'Curso de Gestão de Riscos', group: 'course', classification: 'area-specific', area: 'UAUD' },
  { id: 'curso-compliance', label: 'Curso de Compliance e Regulação', group: 'course', classification: 'transversal' },
  { id: 'curso-seguranca-ti', label: 'Curso de Segurança da Informação', group: 'course', classification: 'area-specific', area: 'UTIC' },
  { id: 'curso-dados', label: 'Curso de Análise de Dados e BI', group: 'course', classification: 'area-specific', area: 'UTIC' },
  { id: 'projeto-transformacao', label: 'Projeto de Transformação Digital', group: 'project', classification: 'transversal' },
  { id: 'projeto-auditoria', label: 'Projeto de Auditoria de Processos', group: 'project', classification: 'area-specific', area: 'UAUD' },
  { id: 'projeto-infra', label: 'Projeto de Infraestrutura de TIC', group: 'project', classification: 'area-specific', area: 'UTIC' },
  { id: 'projeto-governance', label: 'Projeto de Implementação de Governança', group: 'project', classification: 'transversal' },
  { id: 'projeto-compliance', label: 'Projeto de Conformidade Regulatória', group: 'project', classification: 'transversal' },
  { id: 'projeto-gestao-financeira', label: 'Projeto de Otimização Financeira', group: 'project', classification: 'area-specific', area: 'UGE' },
  { id: 'projeto-rh', label: 'Projeto de Modernização de RH', group: 'project', classification: 'area-specific', area: 'UAS' },
  { id: 'certificacao-pmp', label: 'Certificação PMP', group: 'certification', classification: 'transversal' },
  { id: 'certificacao-itil', label: 'Certificação ITIL', group: 'certification', classification: 'area-specific', area: 'UTIC' },
  { id: 'certificacao-cia', label: 'Certificação CIA (Auditor Interno Certificado)', group: 'certification', classification: 'area-specific', area: 'UAUD' },
  { id: 'certificacao-cisa', label: 'Certificação CISA', group: 'certification', classification: 'area-specific', area: 'UTIC' },
  { id: 'certificacao-iso', label: 'Certificação ISO', group: 'certification', classification: 'transversal' },
  { id: 'unit-gab', label: 'GAB', group: 'unit', classification: 'transversal' },
  { id: 'unit-uaud', label: 'UAUD', group: 'unit', classification: 'transversal' },
  { id: 'unit-uri', label: 'URI', group: 'unit', classification: 'transversal' },
  { id: 'unit-uge', label: 'UGE', group: 'unit', classification: 'transversal' },
  { id: 'unit-umc', label: 'UMC', group: 'unit', classification: 'transversal' },
  { id: 'unit-ajur', label: 'AJUR', group: 'unit', classification: 'transversal' },
  { id: 'unit-ugp', label: 'UGP', group: 'unit', classification: 'transversal' },
  { id: 'unit-uas', label: 'UAS', group: 'unit', classification: 'transversal' },
  { id: 'unit-ugoc', label: 'UGOC', group: 'unit', classification: 'transversal' },
  { id: 'unit-utic', label: 'UTIC', group: 'unit', classification: 'transversal' },
  { id: 'unit-urc', label: 'URC', group: 'unit', classification: 'transversal' },
  { id: 'unit-uac', label: 'UAC', group: 'unit', classification: 'transversal' },
  { id: 'unit-regionais', label: 'UNIDADES_REGIONAIS', group: 'unit', classification: 'transversal' },
  { id: 'role-analista', label: 'Analista', group: 'role', classification: 'transversal' },
  { id: 'role-coordenador', label: 'Coordenador', group: 'role', classification: 'transversal' },
  { id: 'role-gerente', label: 'Gerente', group: 'role', classification: 'transversal' },
  { id: 'role-diretor', label: 'Diretor', group: 'role', classification: 'transversal' },
  { id: 'role-assistente', label: 'Assistente', group: 'role', classification: 'transversal' },
  { id: 'grad-administracao', label: 'Administração', group: 'graduation', classification: 'transversal' },
  { id: 'grad-economia', label: 'Economia', group: 'graduation', classification: 'transversal' },
  { id: 'grad-contabilidade', label: 'Contabilidade', group: 'graduation', classification: 'transversal' },
  { id: 'grad-direito', label: 'Direito', group: 'graduation', classification: 'transversal' },
  { id: 'grad-engenharia', label: 'Engenharia', group: 'graduation', classification: 'transversal' },
  { id: 'grad-ti', label: 'Tecnologia da Informação', group: 'graduation', classification: 'transversal' },
  { id: 'grad-comunicacao', label: 'Comunicação', group: 'graduation', classification: 'transversal' },
  { id: 'name-maria-dinamar', label: 'Maria Dinamar', group: 'name', classification: 'transversal' },
  { id: 'name-joao-doe', label: 'João Doe', group: 'name', classification: 'transversal' },
  { id: 'matricula-000000000', label: '000000000', group: 'matricula', classification: 'transversal' },
  { id: 'matricula-12345', label: '12345', group: 'matricula', classification: 'transversal' }
];

export const ADMIN_USER = {
  email: 'admin@aderencia.local',
  password: 'admin123',
  name: 'Administrador'
};
